# hypridle configuration

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = hyprctl dispatch dpms on && sleep 0.5 && hyprctl dispatch dpms on
    inhibit_sleep = 3
}

# 5 min - lock screen
listener {
    timeout = 300
    on-timeout = hyprlock
}

# 8 min - turn off monitors
listener {
    timeout = 480
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && sleep 0.5 && hyprctl dispatch dpms on
}

# 15 min - suspend
listener {
    timeout = 900
    on-timeout = systemctl suspend
}
