# Autostart

# Core components
exec-once = gnome-keyring-daemon --start --components=secrets
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = hypridle
exec-once = hypr-dock
exec-once = dbus-update-activation-environment --all
exec-once = sleep 1 && dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP=Hyprland
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP

# Bar, wallpaper, notifications
exec-once = mpvpaper -p -o "vo=gpu-next hwdec=auto loop-file=yes vd-lavc-threads=1 cache=no fps=24 panscan=1.0" "*" ~/.config/wallpapers/1.mp4
exec-once = dunst
exec-once = waybar
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Cursor
exec-once = hyprctl setcursor Bibata-Modern-Classic 24

# Programs
exec-once = happ
