# programs and variables
$terminal = kitty
$fileManager = dolphin
$menu = rofi -show drun -theme ~/.config/rofi/catppuccin.rasi
$browser = helium
$telegram = Telegram
$ide = zeditor

# keys declaration
$mod = SUPER
$ctrl = CTRL
$shift = SHIFT
$alt = ALT
$tab = TAB

# basic
bind = $mod, Q, killactive
bind = $mod, R, exec, $menu
bind = $mod, L, exec, hyprlock
bind = $mod, D, exec, hypr-dock

# apps
bind = $mod $shift, T, exec, $terminal
bind = $mod $shift, E, exec, $fileManager
bind = $mod $shift, B, exec, $browser
bind = $mod $shift, G, exec, $telegram
bind = $mod $shift, Z, exec, $ide

# screenshots
bind = $mod $shift, S, exec, grim -g "$(slurp)" - | wl-copy

# shutdown components
bind = $mod $shift, M, exec, command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch exit
bind = $mod $shift, R, exec, pkill -SIGUSR2 waybar

# bindings for floating mode
bind = $mod, F, togglefloating,
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# move focus with mod + arrow keys
bind = $mod, left, movefocus, l
bind = $mod, right, movefocus, r
bind = $mod, up, movefocus, u
bind = $mod, down, movefocus, d

# scroll through existing workspaces with mod + scroll
bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1

# move/resize windows in floating mode with mod + lmb/rmb and dragging
bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow

# move windows in normal mode with mod + shift + arrows
bind = $mod $shift, left, movewindow, l
bind = $mod $shift, right, movewindow, r
bind = $mod $shift, up, movewindow, u
bind = $mod $shift, down, movewindow, d

# requires playerctl
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%+
bindl = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 2%-

# switch layout
bind = $mod, SPACE, exec, hyprctl switchxkblayout current next

# bind rofi on alt tab
bind = $alt, $tab, exec, rofi -show window

# workspaces
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

# move window to workspace
bind = $mod $shift, 1, movetoworkspace, 1
bind = $mod $shift, 2, movetoworkspace, 2
bind = $mod $shift, 3, movetoworkspace, 3
bind = $mod $shift, 4, movetoworkspace, 4
bind = $mod $shift, 5, movetoworkspace, 5
bind = $mod $shift, 6, movetoworkspace, 6
bind = $mod $shift, 7, movetoworkspace, 7
bind = $mod $shift, 8, movetoworkspace, 8
bind = $mod $shift, 9, movetoworkspace, 9
bind = $mod $shift, 10, movetoworkspace, 0

# switch workspaces with left right arrows
bind = $ctrl, left, workspace, e-1
bind = $ctrl, right, workspace, e+1

# switch workspaces with MWHEELUP/MWHEELDOWN
bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1
