### Windows & Workspaces

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = blur-kitty
    match:class = kitty

    opacity = 0.92 0.92
}

windowrule {
    name = float-kitty
    match:class = kitty

    float = yes
    center = yes
}

windowrule {
    name = float-mission-center
    match:class = ^(io.missioncenter.MissionCenter)$

    float = yes
    center = yes
    size = 910 610
}

windowrule {
    name = float-telegram
    match:class = ^(org.telegram.desktop)$

    float = yes
    center = yes
    size = 410 860
}

windowrule {
    name = telegram-media-viewer
    match:class = ^(org.telegram.desktop)$
    match:title = (?i)^(Media viewer|Просмотр медиа)$

    float = yes
    center = yes
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = auth-dialogs
    match:title = (?i)^(Authentication Required|Password Required|Unlock Keyring|Authorize|Пароль|Аутентификация)$

    float = yes
    center = yes

    no_focus = true
}

windowrule {
    name = file-picker
    match:title = (?i)^(Open File|Save File|Choose Files|Select File|Открыть файл|Сохранить файл|Open Folder|Открыть папку|Open Files|Открытие файлов)$

    float = yes
    center = yes

    size = 900 700
}

windowrule {
    name = browser-pip
    match:title = (?i).*(Picture[- ]in[- ]Picture|Картинка[- ]в[- ]картинке).*

    float = yes
    pin = yes

    border_size = 0

    size = 374 210
    move = 1517 850
}

# hypr-dock
layerrule = blur true,match:namespace hypr-dock
layerrule = ignore_alpha 0,match:namespace hypr-dock
layerrule = blur true,match:namespace dock-popup
layerrule = ignore_alpha 0,match:namespace dock-popup
