### Windows & Workspaces

windowrule {
    name = suppress-maximize-events
    match:class = .*

    suppress_event = maximize
}

windowrule {
    name = blur-kitty
    match:class = kitty
    opacity = 0.92 0.92
}

windowrule {
    name = telegram-media-viewer
    match:class = ^(org.telegram.desktop)$
    match:title = ^(Media viewer|Просмотр медиа)$

    float = yes
    center = yes
}

windowrule {
    name = fix-xwayland-drags
    match:class = ^$
    match:title = ^$
    match:xwayland = true
    match:float = true
    match:fullscreen = false
    match:pin = false

    no_focus = true
}

windowrule {
    name = move-hyprland-run

    match:class = hyprland-run

    move = 20 monitor_h-120
    float = yes
}

# hypr-dock
layerrule = blur true,match:namespace hypr-dock
layerrule = ignore_alpha 0,match:namespace hypr-dock
layerrule = blur true,match:namespace dock-popup
layerrule = ignore_alpha 0,match:namespace dock-popup
